on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: ./setup.sh
    - run: ./build.sh
    - uses: actions/upload-artifact@v4
      with:
        name: Output documents
        path: ./out/*.pdf
