on:
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout source
      uses: actions/checkout@v4
# check textlint
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - run: npm ci
    - run: npx textlint ./contents/**/*.md >> ./.textlint.log
    - if: ${{ failure() }}
      run: gh pr comment --body-file ./.textlint.log "${URL}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        URL: ${{ github.event.pull_request.html_url }}